### ISSUE TITLE
How to install plugin? 

### ISSUE THREAD

**Issue by JackMordaunt** [gotschmarcel/qtcreator-go#1]
Do you know how to install this plugin on OS X? Any help appreciated :)

**Comment by gotschmarcel** [comment]
@JackMordaunt It has been a while, since I last deployed the project, but I'll get into it again and keep you posted. I'll probably add a README with an explanation too.

Just as an FYI, the plugin only supports simple projects and syntax highlighting - it's in a really early stage. I'd love to continue the development, but that's currently not possible.

**Comment by gotschmarcel** [comment]
@JackMordaunt Sorry for the late response, I was really busy and didn't have any time to look into it until now.

I added a README file explaining how to build the current state. Since you're on mac you should use the QMAKESPEC `macx-clang` for the `qmake` calls. You can also pass `USE_USER_DESTDIR=yes` to the `qmake` call of the plugin to install the plugin.

I hope this helps. If there's any problem just get back at me.

I'm still working on the plugin and it is in a really early stage - just as a side note.
